"""Catalogo stringhe it/en, rilevamento lingua e funzione T().

Regole:
- `T(key)` rende la stringa nella lingua corrente, con fallback all'italiano.
- Le stringhe valutate all'import (BINDINGS, MENU_IT) seguono la lingua
  impostata PRIMA della definizione delle classi (vedi _apply_startup_lang).
- Le stringhe valutate a runtime (compose, notify, system commands) seguono
  sempre la lingua corrente.
"""

import locale

LANGS = ("it", "en")

_current = "it"


def detect_system_lang() -> str:
    """'it' se il sistema e' italiano, altrimenti 'en'.

    Se il locale e' indeterminato (C/POSIX/vuoto) ritorna 'it'
    per non cambiare lingua agli utenti esistenti.
    """
    import os

    try:
        loc = locale.getlocale()[0] or ""
    except Exception:
        loc = ""
    env = " ".join(
        x
        for x in (
            loc,
            os.environ.get("LC_ALL", ""),
            os.environ.get("LANG", ""),
        )
        if x
    )
    if not env or env.upper().startswith(("C.", "C ", "POSIX")):
        return "it"
    low = env.lower()
    if "italian" in low or low.startswith("it") or "_it" in low:
        return "it"
    return "en"


def set_lang(code: str) -> str:
    """Imposta la lingua corrente ('it'/'en'), ritorna quella effettiva."""
    global _current
    _current = "it" if str(code).lower().startswith("it") else "en"
    return _current


def get_lang() -> str:
    return _current


def resolve_lang(cfg_value: str) -> str:
    """'it'/'en' espliciti, altrimenti rilevamento ('auto' o altro)."""
    v = str(cfg_value or "auto").lower()
    if v.startswith("it"):
        return "it"
    if v.startswith("en"):
        return "en"
    return detect_system_lang()


def T(key: str, default: str | None = None, **fmt) -> str:
    """Rende la stringa; fallback it, poi default, poi la chiave stessa."""
    table = STRINGS.get(_current, {})
    text = table.get(
        key, STRINGS["it"].get(key, default if default is not None else key)
    )
    if fmt:
        try:
            return text.format(**fmt)
        except (KeyError, IndexError, ValueError):
            return text
    return text


def key_sections() -> tuple:
    """Sezioni della schermata Tasti nella lingua corrente."""
    return KEY_SECTIONS.get(_current, KEY_SECTIONS["it"])


MONTHS: dict[str, list[str]] = {
    "it": [
        "",
        "Gennaio",
        "Febbraio",
        "Marzo",
        "Aprile",
        "Maggio",
        "Giugno",
        "Luglio",
        "Agosto",
        "Settembre",
        "Ottobre",
        "Novembre",
        "Dicembre",
    ],
    "en": [
        "",
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
    ],
}
DAYS_SHORT: dict[str, list[str]] = {
    "it": ["Lun", "Mar", "Mer", "Gio", "Ven", "Sab", "Dom"],
    "en": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
}
DAYS_LONG: dict[str, list[str]] = {
    "it": [
        "Lunedì",
        "Martedì",
        "Mercoledì",
        "Giovedì",
        "Venerdì",
        "Sabato",
        "Domenica",
    ],
    "en": [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday",
    ],
}
PRIO_LETTERS: dict[str, dict[str, str]] = {
    "it": {"alta": "A", "media": "M", "bassa": "B"},
    "en": {"alta": "H", "media": "M", "bassa": "L"},
}


def months() -> list[str]:
    return MONTHS.get(_current, MONTHS["it"])


def days_short() -> list[str]:
    return DAYS_SHORT.get(_current, DAYS_SHORT["it"])


def days_long() -> list[str]:
    return DAYS_LONG.get(_current, DAYS_LONG["it"])


def prio_letters() -> dict[str, str]:
    return PRIO_LETTERS.get(_current, PRIO_LETTERS["it"])


def prio_disp(value: str) -> str:
    """Nome visualizzato della priorita' ('alta'/'media'/'bassa')."""
    return T(f"prio_{value}", default=value)


def rec_disp(value: str) -> str:
    """Nome visualizzato della ricorrenza ('nessuna'/'giornaliero'/...)."""
    return T(f"rec_{value}", default=value)


def format_date_long(date_str: str) -> str:
    """'2026-09-10' -> 'Giovedì 10 Settembre 2026' / 'Thursday, September 10, 2026'."""
    from datetime import datetime as _dt

    try:
        d = _dt.strptime(date_str, "%Y-%m-%d").date()
    except (ValueError, TypeError):
        return date_str
    if _current == "en":
        return (
            f"{DAYS_LONG['en'][d.weekday()]}, {MONTHS['en'][d.month]} {d.day}, {d.year}"
        )
    try:
        return f"{DAYS_LONG['it'][d.weekday()]} {d.day:02d} {MONTHS['it'][d.month]} {d.year}"
    except IndexError:
        return date_str


STRINGS: dict[str, dict[str, str]] = {
    "it": {
        # Footer / tasti visibili
        "b_quit": "Esci",
        "b_new": "Nuovo",
        "b_subtask": "Sotto-task",
        "b_status": "Stato...",
        "b_edit": "Modifica",
        "b_delete": "Elimina",
        "b_help": "Aiuto",
        "b_search": "Cerca",
        "b_menu": "Menu",
        "b_cancel": "Annulla",
        "b_save": "Salva",
        "b_close": "Chiudi",
        "b_no": "No",
        # Pannello aiuto (h)
        "help_l1": " [bold]TASK:[/bold] [b]n[/b] nuovo  [b]e[/b] modifica  [b]d[/b] elimina  [b]u[/b] annulla  [b]s[/b] sotto-task  [b]Space[/b] stato... [1/2/3]",
        "help_l2": " [bold]VEDI:[/bold] [b]Enter[/b] dettagli  [b]c[/b] calendario  [b]w[/b] settimana  [b]b[/b] mini-kanban  [b]B[/b] kanban-full  [b]p[/b] piano  [b]k[/b] stats  [b]y[/b] salute",
        "help_l3": " [bold]POMO (timer 🍅):[/bold] [b]o[/b] avvia/apri  [b]O[/b] pausa/riprendi  [b]X[/b] completa  (o click sui comandi nella barra rossa)",
        "help_l4": " [bold]FILTRA:[/bold] [b]f[/b] stato  [b]t[/b] tag  [b]g[/b] progetto  [b]/[/b] cerca   [bold]SISTEMA:[/bold] [b]T[/b] template  [b]v[/b] tema  [b]h[/b] aiuto  [b]q[/b] esci",
        "help_l5": " [bold]Stato task:[/bold] [red]O[/red]=Attivo  [yellow]P[/yellow]=Sospeso  [green]X[/green]=Completato   |   [b]m[/b] menu",
        # Menu principale (m)
        "menu_settings_t": "Impostazioni",
        "menu_settings_h": "Tema, vista, obiettivi, durate",
        "menu_health_t": "Salute progetti",
        "menu_health_h": "Avanzamento, ritardi e momentum per progetto",
        "menu_security_t": "Sicurezza",
        "menu_security_h": "Cifratura e password",
        "menu_goals_t": "Obiettivi",
        "menu_goals_h": "Obiettivi giornaliero/settimanale",
        "menu_clearf_t": "Pulisci filtri",
        "menu_clearf_h": "Toglie stato, tag, progetto e ricerca (solo menu)",
        "menu_backup_now_t": "Backup: crea ora",
        "menu_backup_now_h": "Snapshot immediato di tutti i dati",
        "menu_backup_restore_t": "Backup: ripristina",
        "menu_backup_restore_h": "Scegli uno snapshot e ripristina",
        "menu_exp_md_t": "Export: Markdown",
        "menu_exp_md_h": "Export lista leggibile",
        "menu_exp_csv_t": "Export: CSV",
        "menu_exp_csv_h": "Export foglio di calcolo",
        "menu_exp_stats_t": "Export: stats",
        "menu_exp_stats_h": "Export statistiche giornaliere",
        "menu_imp_csv_t": "Importa CSV",
        "menu_imp_csv_h": "Importa da foglio di calcolo",
        "menu_archive_do_t": "Archivia completati",
        "menu_archive_do_h": "Sposta i completati in archivio",
        "menu_archive_view_t": "Archivio",
        "menu_archive_view_h": "Vedi e ripristina archiviati",
        # Comandi di sistema (palette)
        "sys_theme_t": "Tema",
        "sys_theme_h": "Cambia il tema corrente",
        "sys_quit_t": "Esci",
        "sys_quit_h": "Chiudi l'applicazione",
        "sys_keys_t": "Tasti",
        "sys_keys_h": "Elenco completo dei tasti",
        "sys_snap_t": "Istantanea",
        "sys_snap_h": "Salva un'immagine SVG della schermata corrente",
        "pal_placeholder": "Cerca nel menu…",
        "menu_tooltip": "Apri il menu",
        "keys_title": "Tasti — tutte le combinazioni",
        "health_title": "[b]Salute progetti[/b]",
        "health_hint": "Solo task attivi.\nOK = avanti · RISCHIO = attenzione · CRITICO = interveni.",
        "health_empty": "Nessun progetto con task attivi.",
        "health_ok": "OK",
        "health_risk": "A RISCHIO",
        "health_crit": "CRITICO",
        "health_row": "{done}/{tot} fatti · {late} in ritardo · {mom} ultimi 7gg",
        "lock_hint": "Inserisci la password per sbloccare i dati.",
        "lock_open": "Sblocca [enter]",
        "lock_exit": "Esci [esc]",
        "n_lock_bad": "Password errata, riprova.",
        "n_rem_due": "Tra {n} min ({h}): {t}",
        "sec_title": "[b]Sicurezza — cifratura dati[/b]",
        "sec_on": "Stato: [green]protetto[/green] (file cifrati)",
        "sec_off": "Stato: [yellow]non protetto[/yellow] (file in chiaro)",
        "sec_hint": "Dimenticare la password = perdere i dati. Fai prima un backup.",
        "sec_enable": "Attiva protezione",
        "sec_change": "Cambia password",
        "sec_disable": "Disattiva",
        "sec_pw_new": "Nuova password (min 8):",
        "sec_pw_repeat": "Ripeti password:",
        "sec_pw_current": "Password attuale:",
        "sec_pw_title_enable": "[b]Attiva protezione[/b]",
        "sec_pw_title_change": "[b]Cambia password[/b]",
        "sec_pw_title_disable": "[b]Disattiva protezione[/b]",
        "n_sec_need8": "Password troppo corta: minimo 8 caratteri.",
        "n_sec_mismatch": "Le password non coincidono.",
        "n_sec_fill": "Compila tutti i campi.",
        "n_sec_enabled": "Protezione attivata: dati cifrati.",
        "n_sec_changed": "Password cambiata.",
        "n_sec_disabled": "Protezione disattivata: dati in chiaro.",
        "n_sec_badcurrent": "Password attuale errata.",
        "welcome_title": "[b]Benvenuto in Tasko! 🍅[/b]",
        "welcome_body": "Gestisci task, pomodori e statistiche da tastiera.\nCarica i dati di esempio per esplorare, oppure inizia da zero.",
        "welcome_demo": "Carica demo",
        "welcome_empty": "Inizia vuoto",
        "n_welcome_demo": "Dati di esempio caricati: premi 'h' per l'aiuto!",
        "prio_alta": "Alta",
        "prio_media": "Media",
        "prio_bassa": "Bassa",
        "rec_nessuna": "Nessuna",
        "rec_giornaliero": "Giornaliero",
        "rec_settimanale": "Settimanale",
        "rec_mensile": "Mensile",
        "rec_annuale": "Annuale",
        # Form todo
        "form_notes": "Note / Descrizione (supporta - [ ] checklist):",
        "form_project": "Progetto:",
        "form_due": "Scadenza (YYYY-MM-DD [HH:MM]):",
        "form_tags": "Tags:",
        "form_priority": "Priorita:",
        "form_recurrence": "Ricorrenza:",
        "form_title_ph": "Titolo... (es: Chiamare Anna domani 9:00 #casa !alta)",
        "form_project_ph": "es: lavoro",
        "form_due_ph": "es: 2026-09-10 09:00, oggi, domani",
        "form_tags_ph": "es: lavoro,urgente",
        "form_stima": "Stima 🍅:",
        "form_stima_ph": "es: 4",
        "form_save": "Salva [ctrl+enter]",
        "form_cancel": "Annulla [esc]",
        "form_new": "Nuovo Todo",
        "form_edit": "Modifica Todo",
        "form_sub": "Sotto-task di '{parent}'",
        # Conferma / stato / tema
        "confirm_yes": "Sì, elimina",
        "state_title": "Cambia stato di\n[b]{title}[/b]\n(dim: ora {current})",
        "state_attivo": "attivo",
        "state_sospeso": "sospeso",
        "state_completato": "completato",
        "state_btn_attivo": "O Attivo [1]",
        "state_btn_sospeso": "P Sospeso [2]",
        "state_btn_completato": "X Fatto [3]",
        "ui_cancel_esc": "Annulla [esc]",
        "ui_close_esc": "Chiudi [escape]",
        "theme_title": "[b]Scegli il tema [esc per chiudere][/b]",
        # Ricerca
        "search_title": "[b]Cerca in titolo, note, progetto, tag[/b]",
        "search_ph": "es: dentista, #lavoro, sito...",
        "search_clear": "Pulisci",
        # Navigazione
        "nav_prev": "◀ Prec",
        "nav_next": "Succ ▶",
        "week_title": "Settimana {a} - {b}",
        # Template
        "tpl_title": "[b]Template — Usa per creare i task[/b]",
        "tpl_use": "Usa: {name} ({n} task)",
        "tpl_empty": "Nessun template. Creane uno con [b]N[/b].",
        "tpl_new": "Nuovo [n]",
        "tpl_fromproj": "Da progetto [p]",
        "tplc_new": "Nuovo template",
        "tplc_edit": "Modifica template",
        "tplc_name": "Nome template:",
        "tplc_name_ph": "es: Onboarding cliente",
        "tplc_prio": "Priorita' di default:",
        "tplc_tasks": "Task (uno per riga):",
        "tplp_title": "[b]Crea template da progetto[/b]",
        "tplp_row": "{name} ({n} task)",
        "tpldef_client": "Nuovo cliente",
        "tpldef_kickoff": "Kickoff con cliente",
        "tpldef_req": "Raccogli requisiti",
        "tpldef_quote": "Preventivo",
        "tpldef_contract": "Contratto firmato",
        "tpldef_setup": "Setup progetto",
        "tpldef_trip": "Viaggio",
        "tpldef_flights": "Prenota voli",
        "tpldef_hotel": "Prenota hotel",
        "tpldef_checkin": "Check-in online",
        "tpldef_luggage": "Valigia",
        "tpldef_docs": "Documenti",
        "tpldef_site": "Sito web",
        "tpldef_wireframe": "Wireframe",
        "tpldef_design": "Design",
        "tpldef_dev": "Sviluppo",
        "tpldef_test": "Test",
        "tpldef_deploy": "Deploy",
        # Popup pomodoro
        "pomo_t_focus": "🍅 Focus",
        "pomo_t_short": "☕ Pausa corta",
        "pomo_t_long": "☕ Pausa lunga",
        "pomo_phase_short": "Pausa corta",
        "pomo_phase_long": "Pausa lunga",
        "pomo_pause": "Pausa [p]",
        "pomo_resume": "Riprendi [p]",
        "pomo_done": "Completa [x]",
        "pomo_skip": "Salta pausa [x]",
        "pomo_stop": "Annulla timer",
        "pomo_close": "Chiudi [esc]",
        "pomo_dur_focus": "Durata focus (min) [1/2/3]:",
        "pomo_dur_break": "Durata pausa (min) [1/2/3]:",
        # Kanban
        "kb_title": "[b]Kanban — panoramica per stato (sola lettura)[/b]",
        "kb_hint": "Per spostare un task: [b]Esc[/b], selezionalo nella lista e premi [b]Space[/b]",
        "kb_col_attivo": "○ ATTIVO",
        "kb_col_sospeso": "◐ SOSPESO",
        "kb_col_fatto": "● FATTO",
        "kb_more": "+{n} altri",
        # Dettaglio
        "detail_prio": "Priorita:",
        "detail_pomo": "Pomodori:",
        "detail_ric": "Ricorrenza:",
        "detail_state": "Stato:",
        "detail_notes": "[b]Note:[/b]",
        "detail_subs": "[b]Sotto-attivita:[/b]",
        "detail_nosubs": "Nessuna sotto-attivita.",
        "detail_edit": "Modifica [e]",
        "detail_dueline": "Scadenza: {due}  |  Creazione: {created}",
        # Giorno
        "day_title": "Task del {label}",
        "day_empty": "Nessun task attivo in questa data.",
        # Calendario
        "cal_legend": " [b]Legenda:[/b] [red]A[/red]=Alta  [yellow]M[/yellow]=Media  [green]B[/green]=Bassa",
        # Piano
        "plan_title": "Il mio piano - {date}",
        "plan_sec_planned": "[b]Pianificati per oggi (x rimuove, Space sospende){load}:[/b]",
        "plan_sec_due": "[b]Scadono oggi (aggiungi con [cyan]+[/]):[/b]",
        "plan_sec_overdue": "[b][red]In ritardo (aggiungi con [cyan]+[/]):[/red][/b]",
        "plan_sec_unplanned": "[b]Senza scadenza (aggiungi con [cyan]+[/]):[/b]",
        "plan_empty": "[green]Nessun task disponibile per il piano di oggi.[/]",
        "plan_legend": " [b]Comandi:[/b] [cyan]+[/] aggiungi al piano  [cyan]x[/] rimuovi  [cyan]Space[/] sospendi  [cyan]Esc[/] chiudi",
        "plan_load": " (carico 🍅 {f}/{s})",
        "plan_overdue_row": " (scad. {due})",  # Obiettivi
        "goals_title": "[b]Obiettivi[/b]",
        "goals_hint": "Task da completare. 0 = obiettivo disattivato.",
        "goals_daily": "Giornaliero (task):",
        "goals_weekly": "Settimanale (task):",
        "goals_pomo": "Giornaliero (🍅 focus):",
        # Impostazioni
        "set_title": "[b]Impostazioni[/b]",
        "set_theme": "Tema:",
        "set_lang": "Lingua (riavvia per applicare):",
        "set_lang_auto": "Automatica",
        "set_kanban": "Kanban in home:",
        "set_kanban_on": "Visibile",
        "set_kanban_off": "Nascosto",
        "set_filter": "Filtro iniziale:",
        "set_filter_attivo": "Attivi",
        "set_filter_sospeso": "Sospesi",
        "set_filter_completati": "Completati",
        "set_filter_tutti": "Tutti",
        "set_daily": "Obiettivo task/giorno (0=off):",
        "set_weekly": "Obiettivo task/settimana (0=off):",
        "set_pomo": "Obiettivo 🍅/giorno (0=off):",
        "set_focus": "Focus default (min):",
        "set_short": "Pausa corta (min):",
        "set_long": "Pausa lunga (min):",
        "set_every": "Pausa lunga ogni N focus:",
        "set_reminder": "Preavviso scadenze (min, 0=off):",
        "set_sounds": "Suoni:",
        "set_yes": "Sì",
        "set_no": "No",
        # Importazione
        "imp_title": "[b]Importa task da CSV[/b]",
        "imp_empty": "Nessun CSV in Tasko_screenshots: scrivi il percorso sotto.",
        "imp_path": "Percorso file:",
        "imp_path_ph": "~/Tasko_screenshots/tasko_export_….csv",
        "imp_ok": "Importa [ctrl+enter]",
        # Archivio / restore
        "arc_title": "[b]Archivio ({n} task)[/b]",
        "arc_empty": "Archivio vuoto.",
        "arc_all": "Ripristina tutti",
        "rst_title": "[b]Ripristina backup[/b]",
        "rst_empty": "Nessuno snapshot disponibile.",
        "rst_row": "{created} · {n} task · {kb} KB",
        # Barre home dinamiche
        "bar_all": "Tutti",
        "bar_filter": "Filtro:{v}",
        "bar_tag": "Tag:#{v}",
        "bar_proj": "Prog:{v}",
        "bar_search": "Cerca:{v}",
        "kb_head": " [bold]KANBAN [b]b[/b]=nascondi [b]B[/b]=full[/bold]",
        "kb_attivo": "ATTIVO",
        "kb_sospeso": "SOSPESO",
        "kb_fatto": "FATTO",
        "pomo_hint_open": "apri",
        "pomo_hint_pause": "pausa/riprendi",
        "pomo_hint_done": "completa",
        "pomo_hint_skip": "salta",
        "pomo_paused": "IN PAUSA",
        "pomo_almost": "quasi finito!",
        "pomo_break_after": "Pausa dopo '{name}'",
        "pomo_cycle": "Ciclo {dots}",
        "pomo_next_long": "poi pausa lunga",
        "pomo_next_short": "poi pausa corta",
        "pomo_paused_tag": " (pausa)",
        # Statistiche
        "stats_title": "[b]Statistiche produttivita'[/b]",
        "stats_goal_today": " [b]Obiettivo oggi:[/b] {done}/{goal} · serie {cur} gg (max {mx}) 🔥",
        "stats_goal_off": " [dim]Obiettivo giornaliero disattivato (menu Obiettivi)[/]",
        "stats_week": " [b]Settimana:[/b] {now}/{goal} · serie {cur} sett (max {mx})",
        "stats_serie": " [b]Serie:[/b] {n} giorni di fila 🔥",
        "stats_serie_off": " [dim]Serie: completa un task per iniziarla[/]",
        "stats_today": " [b]Oggi:[/b] {n} completati",
        "stats_7": " [b]Ultimi 7 giorni:[/b] {n} completati",
        "stats_30": " [b]Ultimi 30 giorni:[/b] {n} completati",
        "stats_tot": " [b]Totale completati:[/b] {n}",
        "stats_undated": " [dim]di cui senza data: {n}[/]",
        "stats_prio": " [b]Per priorita:[/b] [red]Alta {a}[/] | [yellow]Media {m}[/] | [green]Bassa {b}[/]",
        "stats_pomo": " [b]Pomodori:[/b] oggi {t} · ultimi 14 gg {f} · totale {tot} [red]🍅[/]",
        "stats_proj_t": "[b]Per progetto — ultimi 7 giorni (task · 🍅):[/b]",
        "stats_when_t": "[b]Quando rendi — ultimi 30 giorni (task · 🍅):[/b]",
        "stats_wday_t": "[b]Giorni feriali — ultime 8 settimane (task · 🍅):[/b]",
        "stats_punct": " [b]Puntualita':[/b] {pct}% in tempo ({ok}/{tot} con scadenza)",
        "stats_done14": "[b]Completati — ultimi 14 giorni:[/b]",
        "stats_pomo14": "[b]Pomodori — ultimi 14 giorni:[/b]",
        "stats_peak": "max {n} il {d}",
        "stats_peak_none": "nessun dato negli ultimi 14 giorni",
        "stats_last_today": "ultimo valore = oggi",
        "stats_axis": "{start} ← ultimi 14 giorni → oggi ({today})",
        "stats_heat_t": "[b]Heatmap 🍅 — ultime 26 settimane:[/b]",
        "stats_heat_leg": " [dim]· < ░ < ▒ < ▓ < █ (pomodori/giorno)[/]",
        "slot_night": "Notte",
        "slot_morning": "Mattina",
        "slot_afternoon": "Pomeriggio",
        "slot_evening": "Sera",
        "cli_add_h": "Crea un task",
        "cli_title_h": "Titolo del task",
        "cli_proj_h": "Progetto",
        "cli_due_h": "Scadenza (YYYY-MM-DD [HH:MM], oggi, domani)",
        "cli_prio_h": "alta|media|bassa",
        "cli_tags_h": "Tag separati da virgola",
        "cli_list_h": "Elenca i task",
        "cli_state_h": "attivo|sospeso|completato",
        "cli_projf_h": "Filtra per progetto",
        "cli_porc_h": "Output stabile id|stato|priorita|scadenza|titolo",
        "cli_done_h": "Completa un task",
        "cli_show_h": "Dettaglio testuale di un task",
        "cli_id_h": "ID del task",
        "cli_bad_date": "data non valida: {d}",
        "cli_bad_state": "stato non valido: {s}",
        "cli_notfound": "task #{id} non trovato",
        "cli_show_line": "stato: {s} | priorita: {p} | scadenza: {d}",
        "cli_prio_lab": "priorita: {p}",
        "cli_due_lab": "scadenza: {d}",
        "cli_proj_lab": "progetto: {p}",
        "cli_tags_lab": "tags: {t}",
        "cli_notes_lab": "note: {n}",
        "cli_pomo_lab": "pomodori: {n}",
        "cli_row": "#{id} [{m}] {t}{p} (scad: {d}, prio: {r})",
        "col_state": "Stato",
        "col_title": "Titolo",
        "col_proj": "Prog",
        "col_notes": "Note",
        "col_prio": "Priorita",
        "col_recur": "Ricorr",
        "col_due": "Scadenza",
        # Form: titoli bordo validazione
        "form_need_title": "Obbligatorio!",
        "form_need_date": "Usa YYYY-MM-DD [HH:MM]",
        "form_need_num": "Numero!",
        # Notifiche
        "n_title_req": "Il titolo è obbligatorio.",
        "n_date_bad": "Data non valida: usa YYYY-MM-DD [HH:MM], oggi o domani.",
        "n_stima_bad": "Stima non valida: inserisci un numero intero.",
        "n_tpl_name_req": "Il nome e' obbligatorio.",
        "n_tpl_tasks_req": "Inserisci almeno un task (uno per riga).",
        "n_imp_pick": "Scegli un file dalla lista o scrivi il percorso.",
        "n_plan_add_none": "Nessun task da aggiungere al piano.",
        "n_plan_added": "Aggiunto al piano: {t}",
        "n_plan_rm_none": "Nessun task pianificato da rimuovere.",
        "n_plan_susp_none": "Nessun task pianificato da sospendere.",
        "n_goals_int": "Inserisci numeri interi (0 = disattivato).",
        "n_goals_range": "Range: task 0-100/0-500, 🍅 0-100.",
        "n_set_num": "Campo non valido: inserisci un numero ({lo}-{hi}).",
        "n_set_range": "Campo non valido: range {lo}-{hi}.",
        "n_welcome": "Benvenuto! Premi 'n' per il primo task.",
        "n_nosel": "Nessun todo selezionato!",
        "n_added": "Todo '{t}' aggiunto!",
        "n_updated": "Todo '{t}' aggiornato!",
        "n_deleted": "Todo '{t}' eliminato! Premi 'u' per annullare.",
        "n_del_t": "Eliminare '{t}'?",
        "n_del_sub": "\nVerranno eliminati anche {n} sotto-task.",
        "n_recur": "Prossima occorrenza: {t} (scadenza: {d})",
        "n_to_active": "attivo",
        "n_to_paused": "in sospeso",
        "n_to_done": "completato",
        "n_state": "Todo '{t}' -> {s}!",
        "n_maxdepth": "Limite massimo di {n} livelli raggiunto!",
        "n_sub_added": "Sotto-task '{s}' aggiunto a '{p}'!",
        "n_f_attivo": "solo attivi",
        "n_f_sospeso": "solo in sospeso",
        "n_f_fatti": "solo completati",
        "n_f_tutti": "tutti",
        "n_filter": "Filtro: {v}",
        "n_filters_clear": "Filtri puliti: mostro tutto.",
        "n_notags": "Nessun tag trovato!",
        "n_ftag_all": "Filtro tag: tutti",
        "n_ftag": "Filtro tag: #{t}",
        "n_noproj": "Nessun progetto trovato!",
        "n_fproj_all": "Filtro progetto: tutti",
        "n_fproj": "Filtro progetto: {p}",
        "n_search_clear": "Ricerca pulita",
        "n_search": "Cerca: {q}",
        "n_pomo_start": "🍅 Focus avviato su '{t}' ({m} min).",
        "n_pomo_none": "Nessun pomodoro attivo.",
        "n_timer_none": "Nessun timer attivo.",
        "n_dur_bad": "Durata non valida ({lo}-{hi} min).",
        "n_dur_set": "Durata {m} min (timer riavviato).",
        "n_rest_paused": "⏸ {w} ripristinato in pausa su '{t}'. Premi O per riprendere.",
        "pomo_what_break": "Pausa",
        "pomo_what_focus": "Focus",
        "pomo_what_timer": "Timer",
        "n_rest_cred": "🍅 {n} focus completati mentre l'app era chiusa",
        "n_rest_breakdone": "pausa terminata",
        "n_rest_expired": "Timer scaduto",
        "n_rest_total": "! Totale 🍅 su '{t}': {n}",
        "n_rest_extra": " (+{n} 🍅 accreditati)",
        "n_rest_active": "{icon} {w} ripristinato su '{t}'{extra}.",
        "n_resumed": "Timer ripreso",
        "n_paused": "Timer in pausa",
        "n_stopped": "Timer annullato (ciclo invariato)",
        "n_focus_done": "🍅 Focus completato {name}! Ciclo {dots} — ☕ pausa {kind} da {mins} min (X per saltarla).",
        "pomo_long_w": "lunga",
        "pomo_short_w": "corta",
        "n_skipped": "Pausa saltata (ciclo invariato).",
        "n_long_done": "☕ Pausa lunga finita — si riparte con un nuovo ciclo!",
        "n_short_done": "☕ Pausa finita — pronto per il prossimo focus!",
        "n_kb_show": "Kanban mostrato [b]=nascondi [B]=full",
        "n_kb_hide": "Kanban nascosto",
        "n_nothing": "Nulla da annullare",
        "n_restored": "Ripristinati {n} task!",
        "n_arc_none": "Nessun task completato da archiviare.",
        "n_arc_err": "Errore archiviazione: {e}",
        "n_archived": "Archiviati {n} task! Premi 'u' per annullare.",
        "n_arc_confirm": "Archiviare {n} task completati?\nRestano visibili in menu Archivio.",
        "n_arc_emptied": "Archivio svuotato: ripristinati {n} task!",
        "n_arc_one": "Ripristinato '{t}'!",
        "n_tpl_made": "Template '{n}': creati {c} task!",
        "n_tpl_del": "Template '{n}' eliminato.",
        "n_tpl_confirm": "Eliminare il template '{n}'?",
        "n_tpl_badname": "Nome template non valido.",
        "n_tpl_dup": "Esiste gia' un template '{n}'.",
        "n_tpl_empty": "Il template deve avere almeno un task.",
        "n_tpl_created": "Template '{n}' creato con {c} task!",
        "n_tpl_need": "Nome e almeno un task obbligatori.",
        "n_tpl_updated": "Template '{n}' aggiornato ({c} task)!",
        "n_tpl_noproj": "Nessun progetto trovato nei task.",
        "n_tpl_emptyproj": "Nessun task nel progetto '{p}'.",
        "n_tpl_fromproj": "Template '{n}' creato da progetto '{p}' ({c} task)!",
        "n_exp_saved": "Export salvato: {p}",
        "n_exp_err": "Errore export: {e}",
        "n_stat_saved": "Stats CSV salvato: {p} ({d} giorni)",
        "n_stat_err": "Errore export stats: {e}",
        "n_csv_saved": "CSV salvato: {p} ({n} task)",
        "n_csv_err": "Errore export CSV: {e}",
        "n_imp_err": "Errore import: {e}",
        "n_imp_ok": "Importati {n} task da {f}",
        "n_imp_skip": " ({s} righe scartate)",
        "n_goals_saved": "Obiettivi: {d}/giorno, {w}/settimana, 🍅x{p}/giorno.",
        "n_theme_bad": "Tema non applicabile: {e}",
        "n_theme": "Tema: {c}",
        "n_lang_restart": "Lingua salvata: riavvia l'app per applicarla.",
        "n_settings_saved": "Impostazioni salvate.",
        "n_bak_fail": "Backup fallito: {e}",
        "n_bak_ok": "Backup creato: {n}",
        "n_no_snap": "Nessuno snapshot da ripristinare.",
        "n_restore_fail": "Ripristino fallito: {e}",
        "n_restored_snap": "Ripristinato snapshot {d} (stato precedente salvato).",
        "n_restore_confirm": "Ripristinare lo snapshot {d}?\nLo stato corrente viene salvato prima.",
        "n_restore_badkey": "Dati illeggibili: password errata? Lo stato precedente e' al sicuro.",
        "n_auto_bak": "Backup automatico: {n}",
        "n_reloaded": "Dati ricaricati!",
        "n_shot_saved": "Screenshot salvato: {p}",
        "n_shot_err": "Errore screenshot: {e}",
    },
    "en": {
        # Footer / visible keys
        "b_quit": "Quit",
        "b_new": "New",
        "b_subtask": "Subtask",
        "b_status": "Status...",
        "b_edit": "Edit",
        "b_delete": "Delete",
        "b_help": "Help",
        "b_search": "Search",
        "b_menu": "Menu",
        "b_cancel": "Cancel",
        "b_save": "Save",
        "b_close": "Close",
        "b_no": "No",
        # Help panel (h)
        "help_l1": " [bold]TASKS:[/bold] [b]n[/b] new  [b]e[/b] edit  [b]d[/b] delete  [b]u[/b] undo  [b]s[/b] subtask  [b]Space[/b] status... [1/2/3]",
        "help_l2": " [bold]VIEWS:[/bold] [b]Enter[/b] details  [b]c[/b] calendar  [b]w[/b] week  [b]b[/b] mini-kanban  [b]B[/b] kanban-full  [b]p[/b] plan  [b]k[/b] stats  [b]y[/b] health",
        "help_l3": " [bold]POMO (🍅 timer):[/bold] [b]o[/b] start/open  [b]O[/b] pause/resume  [b]X[/b] complete  (or click the commands in the red bar)",
        "help_l4": " [bold]FILTER:[/bold] [b]f[/b] state  [b]t[/b] tag  [b]g[/b] project  [b]/[/b] search   [bold]SYSTEM:[/bold] [b]T[/b] template  [b]v[/b] theme  [b]h[/b] help  [b]q[/b] quit",
        "help_l5": " [bold]Task state:[/bold] [red]O[/red]=Active  [yellow]P[/yellow]=Paused  [green]X[/green]=Done   |   [b]m[/b] menu",
        # Main menu (m)
        "menu_settings_t": "Settings",
        "menu_settings_h": "Theme, view, goals, durations",
        "menu_health_t": "Project health",
        "menu_health_h": "Progress, overdue and momentum per project",
        "menu_security_t": "Security",
        "menu_security_h": "Encryption and password",
        "menu_goals_t": "Goals",
        "menu_goals_h": "Daily/weekly goals",
        "menu_clearf_t": "Clear filters",
        "menu_clearf_h": "Clears state, tag, project and search (menu only)",
        "menu_backup_now_t": "Backup: create now",
        "menu_backup_now_h": "Immediate snapshot of all data",
        "menu_backup_restore_t": "Backup: restore",
        "menu_backup_restore_h": "Pick a snapshot and restore",
        "menu_exp_md_t": "Export: Markdown",
        "menu_exp_md_h": "Readable list export",
        "menu_exp_csv_t": "Export: CSV",
        "menu_exp_csv_h": "Spreadsheet export",
        "menu_exp_stats_t": "Export: stats",
        "menu_exp_stats_h": "Daily stats export",
        "menu_imp_csv_t": "Import CSV",
        "menu_imp_csv_h": "Import from spreadsheet",
        "menu_archive_do_t": "Archive completed",
        "menu_archive_do_h": "Move completed to archive",
        "menu_archive_view_t": "Archive",
        "menu_archive_view_h": "View and restore archived",
        # System commands (palette)
        "sys_theme_t": "Theme",
        "sys_theme_h": "Change the current theme",
        "sys_quit_t": "Quit",
        "sys_quit_h": "Quit the application",
        "sys_keys_t": "Keys",
        "sys_keys_h": "Full key list",
        "sys_snap_t": "Snapshot",
        "sys_snap_h": "Save an SVG screenshot of the current screen",
        "pal_placeholder": "Search the menu…",
        "menu_tooltip": "Open the menu",
        "keys_title": "Keys — all combinations",
        "health_title": "[b]Project health[/b]",
        "health_hint": "Active tasks only.\nOK = on track · AT RISK = attention · CRITICAL = act.",
        "health_empty": "No projects with active tasks.",
        "health_ok": "OK",
        "health_risk": "AT RISK",
        "health_crit": "CRITICAL",
        "health_row": "{done}/{tot} done · {late} overdue · {mom} last 7d",
        "lock_hint": "Enter the password to unlock your data.",
        "lock_open": "Unlock [enter]",
        "lock_exit": "Quit [esc]",
        "n_lock_bad": "Wrong password, try again.",
        "n_rem_due": "In {n} min ({h}): {t}",
        "sec_title": "[b]Security — data encryption[/b]",
        "sec_on": "Status: [green]protected[/green] (encrypted files)",
        "sec_off": "Status: [yellow]unprotected[/yellow] (plain files)",
        "sec_hint": "Forgetting the password = losing the data. Back up first.",
        "sec_enable": "Enable protection",
        "sec_change": "Change password",
        "sec_disable": "Disable",
        "sec_pw_new": "New password (min 8):",
        "sec_pw_repeat": "Repeat password:",
        "sec_pw_current": "Current password:",
        "sec_pw_title_enable": "[b]Enable protection[/b]",
        "sec_pw_title_change": "[b]Change password[/b]",
        "sec_pw_title_disable": "[b]Disable protection[/b]",
        "n_sec_need8": "Password too short: minimum 8 characters.",
        "n_sec_mismatch": "Passwords do not match.",
        "n_sec_fill": "Fill in all fields.",
        "n_sec_enabled": "Protection enabled: data encrypted.",
        "n_sec_changed": "Password changed.",
        "n_sec_disabled": "Protection disabled: plain data.",
        "n_sec_badcurrent": "Wrong current password.",
        "welcome_title": "[b]Welcome to Tasko! 🍅[/b]",
        "welcome_body": "Manage tasks, pomodoros and stats from the keyboard.\nLoad the demo data to explore, or start empty.",
        "welcome_demo": "Load demo",
        "welcome_empty": "Start empty",
        "n_welcome_demo": "Demo data loaded: press 'h' for help!",
        "prio_alta": "High",
        "prio_media": "Medium",
        "prio_bassa": "Low",
        "rec_nessuna": "None",
        "rec_giornaliero": "Daily",
        "rec_settimanale": "Weekly",
        "rec_mensile": "Monthly",
        "rec_annuale": "Yearly",
        # Todo form
        "form_notes": "Notes / Description (supports - [ ] checklist):",
        "form_project": "Project:",
        "form_due": "Due (YYYY-MM-DD [HH:MM]):",
        "form_tags": "Tags:",
        "form_priority": "Priority:",
        "form_recurrence": "Recurrence:",
        "form_title_ph": "Title... (e.g. Call Anna tomorrow 9:00 #home !high)",
        "form_project_ph": "e.g. work",
        "form_due_ph": "e.g. 2026-09-10 09:00, today, tomorrow",
        "form_tags_ph": "e.g. work,urgent",
        "form_stima": "Estimate 🍅:",
        "form_stima_ph": "e.g. 4",
        "form_save": "Save [ctrl+enter]",
        "form_cancel": "Cancel [esc]",
        "form_new": "New Todo",
        "form_edit": "Edit Todo",
        "form_sub": "Subtask of '{parent}'",
        # Confirm / state / theme
        "confirm_yes": "Yes, delete",
        "state_title": "Change state of\n[b]{title}[/b]\n(currently: {current})",
        "state_attivo": "active",
        "state_sospeso": "paused",
        "state_completato": "done",
        "state_btn_attivo": "O Active [1]",
        "state_btn_sospeso": "P Paused [2]",
        "state_btn_completato": "X Done [3]",
        "ui_cancel_esc": "Cancel [esc]",
        "ui_close_esc": "Close [escape]",
        "theme_title": "[b]Pick a theme [esc to close][/b]",
        # Search
        "search_title": "[b]Search title, notes, project, tags[/b]",
        "search_ph": "e.g. dentist, #work, site...",
        "search_clear": "Clear",
        # Navigation
        "nav_prev": "◀ Prev",
        "nav_next": "Next ▶",
        "week_title": "Week {a} - {b}",
        # Templates
        "tpl_title": "[b]Templates — Use to create tasks[/b]",
        "tpl_use": "Use: {name} ({n} tasks)",
        "tpl_empty": "No templates. Create one with [b]N[/b].",
        "tpl_new": "New [n]",
        "tpl_fromproj": "From project [p]",
        "tplc_new": "New template",
        "tplc_edit": "Edit template",
        "tplc_name": "Template name:",
        "tplc_name_ph": "e.g. Client onboarding",
        "tplc_prio": "Default priority:",
        "tplc_tasks": "Tasks (one per line):",
        "tplp_title": "[b]Create template from project[/b]",
        "tplp_row": "{name} ({n} tasks)",
        "tpldef_client": "New client",
        "tpldef_kickoff": "Client kickoff",
        "tpldef_req": "Gather requirements",
        "tpldef_quote": "Quote",
        "tpldef_contract": "Signed contract",
        "tpldef_setup": "Project setup",
        "tpldef_trip": "Trip",
        "tpldef_flights": "Book flights",
        "tpldef_hotel": "Book hotel",
        "tpldef_checkin": "Online check-in",
        "tpldef_luggage": "Pack suitcase",
        "tpldef_docs": "Documents",
        "tpldef_site": "Website",
        "tpldef_wireframe": "Wireframe",
        "tpldef_design": "Design",
        "tpldef_dev": "Development",
        "tpldef_test": "Testing",
        "tpldef_deploy": "Deploy",
        # Pomodoro popup
        "pomo_t_focus": "🍅 Focus",
        "pomo_t_short": "☕ Short break",
        "pomo_t_long": "☕ Long break",
        "pomo_phase_short": "Short break",
        "pomo_phase_long": "Long break",
        "pomo_pause": "Pause [p]",
        "pomo_resume": "Resume [p]",
        "pomo_done": "Complete [x]",
        "pomo_skip": "Skip break [x]",
        "pomo_stop": "Cancel timer",
        "pomo_close": "Close [esc]",
        "pomo_dur_focus": "Focus length (min) [1/2/3]:",
        "pomo_dur_break": "Break length (min) [1/2/3]:",
        # Kanban
        "kb_title": "[b]Kanban — state overview (read only)[/b]",
        "kb_hint": "To move a task: [b]Esc[/b], select it in the list and press [b]Space[/b]",
        "kb_col_attivo": "○ ACTIVE",
        "kb_col_sospeso": "◐ PAUSED",
        "kb_col_fatto": "● DONE",
        "kb_more": "+{n} more",
        # Details
        "detail_prio": "Priority:",
        "detail_pomo": "Pomodoros:",
        "detail_ric": "Recurrence:",
        "detail_state": "State:",
        "detail_notes": "[b]Notes:[/b]",
        "detail_subs": "[b]Subtasks:[/b]",
        "detail_nosubs": "No subtasks.",
        "detail_edit": "Edit [e]",
        "detail_dueline": "Due: {due}  |  Created: {created}",
        # Day
        "day_title": "Tasks for {label}",
        "day_empty": "No active tasks on this date.",
        # Calendar
        "cal_legend": " [b]Legend:[/b] [red]H[/red]=High  [yellow]M[/yellow]=Medium  [green]L[/green]=Low",
        # Plan
        "plan_title": "My plan - {date}",
        "plan_sec_planned": "[b]Planned for today (x removes, Space pauses){load}:[/b]",
        "plan_sec_due": "[b]Due today (add with [cyan]+[/]):[/b]",
        "plan_sec_overdue": "[b][red]Overdue (add with [cyan]+[/]):[/red][/b]",
        "plan_sec_unplanned": "[b]No due date (add with [cyan]+[/]):[/b]",
        "plan_empty": "[green]No tasks available for today's plan.[/]",
        "plan_legend": " [b]Commands:[/b] [cyan]+[/] add to plan  [cyan]x[/] remove  [cyan]Space[/] pause  [cyan]Esc[/] close",
        "plan_load": " (🍅 load {f}/{s})",
        "plan_overdue_row": " (due {due})",
        # Goals
        "goals_title": "[b]Goals[/b]",
        "goals_hint": "Tasks to complete. 0 = goal off.",
        "goals_daily": "Daily (tasks):",
        "goals_weekly": "Weekly (tasks):",
        "goals_pomo": "Daily (🍅 focus):",
        # Settings
        "set_title": "[b]Settings[/b]",
        "set_theme": "Theme:",
        "set_lang": "Language (restart to apply):",
        "set_lang_auto": "Automatic",
        "set_kanban": "Kanban on home:",
        "set_kanban_on": "Visible",
        "set_kanban_off": "Hidden",
        "set_filter": "Startup filter:",
        "set_filter_attivo": "Active",
        "set_filter_sospeso": "Paused",
        "set_filter_completati": "Done",
        "set_filter_tutti": "All",
        "set_daily": "Daily task goal (0=off):",
        "set_weekly": "Weekly task goal (0=off):",
        "set_pomo": "Daily 🍅 goal (0=off):",
        "set_focus": "Default focus (min):",
        "set_short": "Short break (min):",
        "set_long": "Long break (min):",
        "set_every": "Long break every N focuses:",
        "set_reminder": "Deadline lead time (min, 0=off):",
        "set_sounds": "Sounds:",
        "set_yes": "Yes",
        "set_no": "No",
        # Import
        "imp_title": "[b]Import tasks from CSV[/b]",
        "imp_empty": "No CSV in Tasko_screenshots: type the path below.",
        "imp_path": "File path:",
        "imp_path_ph": "~/Tasko_screenshots/tasko_export_….csv",
        "imp_ok": "Import [ctrl+enter]",
        # Archive / restore
        "arc_title": "[b]Archive ({n} tasks)[/b]",
        "arc_empty": "Archive is empty.",
        "arc_all": "Restore all",
        "rst_title": "[b]Restore backup[/b]",
        "rst_empty": "No snapshots available.",
        "rst_row": "{created} · {n} tasks · {kb} KB",
        "bar_all": "All",
        "bar_filter": "Filter:{v}",
        "bar_tag": "Tag:#{v}",
        "bar_proj": "Proj:{v}",
        "bar_search": "Search:{v}",
        "kb_head": " [bold]KANBAN [b]b[/b]=hide [b]B[/b]=full[/bold]",
        "kb_attivo": "ACTIVE",
        "kb_sospeso": "PAUSED",
        "kb_fatto": "DONE",
        "pomo_hint_open": "open",
        "pomo_hint_pause": "pause/resume",
        "pomo_hint_done": "complete",
        "pomo_hint_skip": "skip",
        "pomo_paused": "PAUSED",
        "pomo_almost": "almost done!",
        "pomo_break_after": "Break after '{name}'",
        "pomo_cycle": "Cycle {dots}",
        "pomo_next_long": "then long break",
        "pomo_next_short": "then short break",
        "pomo_paused_tag": " (paused)",
        # Stats
        "stats_title": "[b]Productivity stats[/b]",
        "stats_goal_today": " [b]Today's goal:[/b] {done}/{goal} · streak {cur} days (max {mx}) 🔥",
        "stats_goal_off": " [dim]Daily goal off (Goals menu)[/]",
        "stats_week": " [b]Week:[/b] {now}/{goal} · streak {cur} weeks (max {mx})",
        "stats_serie": " [b]Streak:[/b] {n} days in a row 🔥",
        "stats_serie_off": " [dim]Streak: complete a task to start one[/]",
        "stats_today": " [b]Today:[/b] {n} done",
        "stats_7": " [b]Last 7 days:[/b] {n} done",
        "stats_30": " [b]Last 30 days:[/b] {n} done",
        "stats_tot": " [b]Total done:[/b] {n}",
        "stats_undated": " [dim]of which undated: {n}[/]",
        "stats_prio": " [b]By priority:[/b] [red]High {a}[/] | [yellow]Medium {m}[/] | [green]Low {b}[/]",
        "stats_pomo": " [b]Pomodoros:[/b] today {t} · last 14 days {f} · total {tot} [red]🍅[/]",
        "stats_proj_t": "[b]By project — last 7 days (tasks · 🍅):[/b]",
        "stats_when_t": "[b]When you deliver — last 30 days (tasks · 🍅):[/b]",
        "stats_wday_t": "[b]Weekdays — last 8 weeks (tasks · 🍅):[/b]",
        "stats_punct": " [b]On time:[/b] {pct}% ({ok}/{tot} with due date)",
        "stats_done14": "[b]Done — last 14 days:[/b]",
        "stats_pomo14": "[b]Pomodoros — last 14 days:[/b]",
        "stats_peak": "max {n} on {d}",
        "stats_peak_none": "no data in the last 14 days",
        "stats_last_today": "last value = today",
        "stats_axis": "{start} ← last 14 days → today ({today})",
        "stats_heat_t": "[b]🍅 Heatmap — last 26 weeks:[/b]",
        "stats_heat_leg": " [dim]· < ░ < ▒ < ▓ < █ (pomodoros/day)[/]",
        "slot_night": "Night",
        "slot_morning": "Morning",
        "slot_afternoon": "Afternoon",
        "slot_evening": "Evening",
        "cli_add_h": "Create a task",
        "cli_title_h": "Task title",
        "cli_proj_h": "Project",
        "cli_due_h": "Due (YYYY-MM-DD [HH:MM], today, tomorrow)",
        "cli_prio_h": "high|medium|low",
        "cli_tags_h": "Comma-separated tags",
        "cli_list_h": "List tasks",
        "cli_state_h": "active|paused|done",
        "cli_projf_h": "Filter by project",
        "cli_porc_h": "Stable output id|state|priority|due|title",
        "cli_done_h": "Complete a task",
        "cli_show_h": "Textual detail of a task",
        "cli_id_h": "Task ID",
        "cli_bad_date": "invalid date: {d}",
        "cli_bad_state": "invalid state: {s}",
        "cli_notfound": "task #{id} not found",
        "cli_show_line": "state: {s} | priority: {p} | due: {d}",
        "cli_prio_lab": "priority: {p}",
        "cli_due_lab": "due: {d}",
        "cli_proj_lab": "project: {p}",
        "cli_tags_lab": "tags: {t}",
        "cli_notes_lab": "notes: {n}",
        "cli_pomo_lab": "pomodoros: {n}",
        "cli_row": "#{id} [{m}] {t}{p} (due: {d}, prio: {r})",
        "col_state": "State",
        "col_title": "Title",
        "col_proj": "Proj",
        "col_notes": "Notes",
        "col_prio": "Priority",
        "col_recur": "Recur",
        "col_due": "Due",
        "form_need_title": "Required!",
        "form_need_date": "Use YYYY-MM-DD [HH:MM]",
        "form_need_num": "Number!",
        "n_title_req": "Title is required.",
        "n_date_bad": "Invalid date: use YYYY-MM-DD [HH:MM], today or tomorrow.",
        "n_stima_bad": "Invalid estimate: enter an integer.",
        "n_tpl_name_req": "Name is required.",
        "n_tpl_tasks_req": "Enter at least one task (one per line).",
        "n_imp_pick": "Pick a file from the list or type the path.",
        "n_plan_add_none": "No tasks to add to the plan.",
        "n_plan_added": "Added to plan: {t}",
        "n_plan_rm_none": "No planned tasks to remove.",
        "n_plan_susp_none": "No planned tasks to pause.",
        "n_goals_int": "Enter integers (0 = off).",
        "n_goals_range": "Range: tasks 0-100/0-500, 🍅 0-100.",
        "n_set_num": "Invalid field: enter a number ({lo}-{hi}).",
        "n_set_range": "Invalid field: range {lo}-{hi}.",
        "n_welcome": "Welcome! Press 'n' for your first task.",
        "n_nosel": "No todo selected!",
        "n_added": "Todo '{t}' added!",
        "n_updated": "Todo '{t}' updated!",
        "n_deleted": "Todo '{t}' deleted! Press 'u' to undo.",
        "n_del_t": "Delete '{t}'?",
        "n_del_sub": "\n{n} subtasks will also be deleted.",
        "n_recur": "Next occurrence: {t} (due: {d})",
        "n_to_active": "active",
        "n_to_paused": "paused",
        "n_to_done": "done",
        "n_state": "Todo '{t}' -> {s}!",
        "n_maxdepth": "Maximum {n} levels reached!",
        "n_sub_added": "Subtask '{s}' added to '{p}'!",
        "n_f_attivo": "active only",
        "n_f_sospeso": "paused only",
        "n_f_fatti": "done only",
        "n_f_tutti": "all",
        "n_filter": "Filter: {v}",
        "n_filters_clear": "Filters cleared: showing all.",
        "n_notags": "No tags found!",
        "n_ftag_all": "Tag filter: all",
        "n_ftag": "Tag filter: #{t}",
        "n_noproj": "No projects found!",
        "n_fproj_all": "Project filter: all",
        "n_fproj": "Project filter: {p}",
        "n_search_clear": "Search cleared",
        "n_search": "Search: {q}",
        "n_pomo_start": "🍅 Focus started on '{t}' ({m} min).",
        "n_pomo_none": "No active pomodoro.",
        "n_timer_none": "No active timer.",
        "n_dur_bad": "Invalid duration ({lo}-{hi} min).",
        "n_dur_set": "Duration {m} min (timer restarted).",
        "n_rest_paused": "⏸ {w} restored paused on '{t}'. Press O to resume.",
        "pomo_what_break": "Break",
        "pomo_what_focus": "Focus",
        "pomo_what_timer": "Timer",
        "n_rest_cred": "🍅 {n} focuses completed while the app was closed",
        "n_rest_breakdone": "break over",
        "n_rest_expired": "Timer expired",
        "n_rest_total": "! 🍅 total on '{t}': {n}",
        "n_rest_extra": " (+{n} 🍅 credited)",
        "n_rest_active": "{icon} {w} restored on '{t}'{extra}.",
        "n_resumed": "Timer resumed",
        "n_paused": "Timer paused",
        "n_stopped": "Timer cancelled (cycle kept)",
        "n_focus_done": "🍅 Focus completed {name}! Cycle {dots} — ☕ {kind} break of {mins} min (X to skip).",
        "pomo_long_w": "long",
        "pomo_short_w": "short",
        "n_skipped": "Break skipped (cycle kept).",
        "n_long_done": "☕ Long break over — starting a new cycle!",
        "n_short_done": "☕ Break over — ready for the next focus!",
        "n_kb_show": "Kanban shown [b]=hide [B]=full",
        "n_kb_hide": "Kanban hidden",
        "n_nothing": "Nothing to undo",
        "n_restored": "Restored {n} tasks!",
        "n_arc_none": "No completed tasks to archive.",
        "n_arc_err": "Archive error: {e}",
        "n_archived": "Archived {n} tasks! Press 'u' to undo.",
        "n_arc_confirm": "Archive {n} completed tasks?\nThey stay visible in the Archive menu.",
        "n_arc_emptied": "Archive emptied: restored {n} tasks!",
        "n_arc_one": "Restored '{t}'!",
        "n_tpl_made": "Template '{n}': created {c} tasks!",
        "n_tpl_del": "Template '{n}' deleted.",
        "n_tpl_confirm": "Delete template '{n}'?",
        "n_tpl_badname": "Invalid template name.",
        "n_tpl_dup": "Template '{n}' already exists.",
        "n_tpl_empty": "Template needs at least one task.",
        "n_tpl_created": "Template '{n}' created with {c} tasks!",
        "n_tpl_need": "Name and at least one task required.",
        "n_tpl_updated": "Template '{n}' updated ({c} tasks)!",
        "n_tpl_noproj": "No projects found in tasks.",
        "n_tpl_emptyproj": "No tasks in project '{p}'.",
        "n_tpl_fromproj": "Template '{n}' created from project '{p}' ({c} tasks)!",
        "n_exp_saved": "Export saved: {p}",
        "n_exp_err": "Export error: {e}",
        "n_stat_saved": "Stats CSV saved: {p} ({d} days)",
        "n_stat_err": "Stats export error: {e}",
        "n_csv_saved": "CSV saved: {p} ({n} tasks)",
        "n_csv_err": "CSV export error: {e}",
        "n_imp_err": "Import error: {e}",
        "n_imp_ok": "Imported {n} tasks from {f}",
        "n_imp_skip": " ({s} rows skipped)",
        "n_goals_saved": "Goals: {d}/day, {w}/week, 🍅x{p}/day.",
        "n_theme_bad": "Theme failed: {e}",
        "n_theme": "Theme: {c}",
        "n_lang_restart": "Language saved: restart the app to apply.",
        "n_settings_saved": "Settings saved.",
        "n_bak_fail": "Backup failed: {e}",
        "n_bak_ok": "Backup created: {n}",
        "n_no_snap": "No snapshots to restore.",
        "n_restore_fail": "Restore failed: {e}",
        "n_restored_snap": "Restored snapshot {d} (previous state saved).",
        "n_restore_confirm": "Restore snapshot {d}?\nCurrent state is saved first.",
        "n_restore_badkey": "Unreadable data: wrong password? Previous state is safe.",
        "n_auto_bak": "Automatic backup: {n}",
        "n_reloaded": "Data reloaded!",
        "n_shot_saved": "Screenshot saved: {p}",
        "n_shot_err": "Screenshot error: {e}",
    },
}

KEY_SECTIONS: dict[str, tuple] = {
    "it": (
        (
            "TASK",
            (
                ("n", "Nuovo todo"),
                ("e", "Modifica selezionato"),
                ("d", "Elimina (con conferma)"),
                ("u", "Annulla eliminazione"),
                ("s", "Sotto-task del selezionato"),
                ("Space", "Cambia stato → 1 Attivo, 2 Sospeso, 3 Fatto"),
                ("Enter", "Dettagli (e = modifica)"),
            ),
        ),
        (
            "VISTE",
            (
                ("c", "Calendario mensile (click giorno = task)"),
                ("w", "Settimana Lun-Dom"),
                ("b", "Mini-kanban in home (mostra/nascondi)"),
                ("B", "Kanban full"),
                ("p", "Piano giorno (+ aggiungi, x rimuovi, Space sospendi)"),
                ("k", "Statistiche"),
            ),
        ),
        (
            "POMODORO",
            (
                ("o", "Avvia timer / apri popup (ovunque)"),
                ("O", "Pausa / riprendi (ovunque)"),
                ("X", "Completa subito (ovunque)"),
                ("p, x, 1/2/3", "Nel popup: pausa, completa, durata 15/25/50"),
            ),
        ),
        (
            "FILTRA / CERCA",
            (
                ("f", "Filtro stato (ciclo)"),
                ("t", "Filtro tag (ciclo)"),
                ("g", "Filtro progetto (ciclo)"),
                ("/", "Cerca (Enter conferma, Esc chiude)"),
                ("menu", "Pulisci filtri (voce dedicata)"),
            ),
        ),
        (
            "SISTEMA",
            (
                ("T", "Template (n nuovo, p da progetto, X elimina)"),
                ("y", "Salute progetti"),
                ("m", "Questo menu"),
                ("v", "Tema"),
                ("h", "Aiuto rapido (mostra/nascondi)"),
                ("ctrl+s", "Screenshot SVG"),
                ("ctrl+e", "Export Markdown"),
                ("r", "Ricarica dati"),
                ("q", "Esci"),
                ("esc", "Chiudi popup"),
                ("ctrl+enter", "Salva nei form"),
                ("Tab", "Passa al campo/bottone successivo"),
            ),
        ),
        (
            "STATO TASK",
            (
                ("O", "Attivo"),
                ("P", "In sospeso"),
                ("X", "Completato"),
            ),
        ),
    ),
    "en": (
        (
            "TASKS",
            (
                ("n", "New todo"),
                ("e", "Edit selected"),
                ("d", "Delete (with confirm)"),
                ("u", "Undo delete"),
                ("s", "Subtask of selected"),
                ("Space", "Change state → 1 Active, 2 Paused, 3 Done"),
                ("Enter", "Details (e = edit)"),
            ),
        ),
        (
            "VIEWS",
            (
                ("c", "Monthly calendar (click day = tasks)"),
                ("w", "Mon-Sun week"),
                ("b", "Home mini-kanban (show/hide)"),
                ("B", "Full kanban"),
                ("p", "Day plan (+ add, x remove, Space pause)"),
                ("k", "Statistics"),
            ),
        ),
        (
            "POMODORO",
            (
                ("o", "Start timer / open popup (anywhere)"),
                ("O", "Pause / resume (anywhere)"),
                ("X", "Complete now (anywhere)"),
                ("p, x, 1/2/3", "In popup: pause, complete, 15/25/50 duration"),
            ),
        ),
        (
            "FILTER / SEARCH",
            (
                ("f", "State filter (cycle)"),
                ("t", "Tag filter (cycle)"),
                ("g", "Project filter (cycle)"),
                ("/", "Search (Enter confirms, Esc closes)"),
                ("menu", "Clear filters (dedicated entry)"),
            ),
        ),
        (
            "SYSTEM",
            (
                ("T", "Templates (n new, p from project, X delete)"),
                ("y", "Project health"),
                ("m", "This menu"),
                ("v", "Theme"),
                ("h", "Quick help (show/hide)"),
                ("ctrl+s", "SVG screenshot"),
                ("ctrl+e", "Markdown export"),
                ("r", "Reload data"),
                ("q", "Quit"),
                ("esc", "Close popup"),
                ("ctrl+enter", "Save in forms"),
                ("Tab", "Next field/button"),
            ),
        ),
        (
            "TASK STATE",
            (
                ("O", "Active"),
                ("P", "Paused"),
                ("X", "Done"),
            ),
        ),
    ),
}
